---
# Source: screen-play/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: RELEASE-NAME-screen-play
  labels:
    app: screen-play
    release: RELEASE-NAME
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: screen-play
    tier: frontend
---
# Source: screen-play/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: RELEASE-NAME-screen-play-server
  labels:
    app: screen-play
    release: RELEASE-NAME
spec:
  type: ClusterIP
  ports:
    - port: 5001
      targetPort: 5001
      protocol: TCP
      name: postgres
  selector:
    app: screen-play
    tier: backend
---
# Source: screen-play/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: RELEASE-NAME-screen-play
  labels:
    app: screen-play
    release: RELEASE-NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app: screen-play
  template:
    metadata:
      labels:
        app: screen-play
    spec:
      volumes:
        - name: s3-bucket
          persistentVolumeClaim:
            claimName: s3-pvc
            readOnly: false
      containers:
        - name: postgres
          image: postgres:17
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: s3-bucket
              mountPath: /var/lib/postgresql/data
              subPath: postgres
          env:
            - name: POSTGRES_DB
              value: ScreenPlay
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_PASSWORD
              value: 
        - name: screenplay
          image: ghcr.io/palacplus/screen-play:1.0.0
          ports:
            - containerPort: 80

        - name: screenplay-server
          image: ghcr.io/palacplus/screen-play-server:1.0.0
          ports:
            - containerPort: 5001
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 5
          env:
            - name: SP_CONNECTIONSTRINGS__DEFAULTCONNECTION
              value: Server=postgres;Port=%!d(string=5432);Database=ScreenPlay;User Id=admin;Password=;
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
            - name: SP_AUTHENTICATION__GOOGLE__CLIENTID
              value: ""
            - name: SP_AUTHENTICATION__GOOGLE__CLIENTSECRET
              value: ""
            - name: SP_AUTHENTICATION__JWT__KEY
              value: ""
            - name: SP_AUTHENTICATION__JWT__ISSUER
              value: screenplay
            - name: SP_AUTHENTICATION__JWT__AUDIENCE
              value: screenplay
            - name: SP_AUTHENTICATION__JWT__EXPIRYHOURS
              value: "1"
            - name: SP_ADMIN__EMAIL
              value: ""
            - name: SP_ADMIN__PASSWORD
              value: ""
            - name: SP_RADARR__URI
              value: http://radarr:7878
            - name: SP_RADARR__APIKEY
              value: ""
            - name: SP_RADARR__ROOTFOLDERPATH
              value: /movies
          resources:
            requests:
            limits:
              cpu: 1
              memory: 400M
            requests:
              cpu: 1
              memory: 128M
