apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm-chart.fullname" . }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "helm-chart.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "helm-chart.name" . }}
    spec:
      containers:
        - name: postgres
          image: {{ include "helm-chart.postgres.image" . }}
          ports:
            - containerPort: {{ .Values.postgres.containerPort }}
          env:
{{ toYaml .Values.postgres.env | indent 12 }}

        - name: screenplay-server
          image: {{ include "helm-chart.server.image" . }}
          ports:
            - containerPort: {{ .Values.server.containerPort }}
          readinessProbe:
{{ toYaml .Values.server.readinessProbe | indent 12 }}
          env:
{{ toYaml .Values.server.env | indent 12 }}

        - name: screenplay
          image: {{ include "helm-chart.frontend.image" . }}
          ports:
            - containerPort: {{ .Values.frontend.containerPort }}
