apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm-chart.fullname" . }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "helm-chart.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "helm-chart.name" . }}
    spec:
      volumes:
      {{- range .Values.postgres.volumes }}
        - name: {{ .name }}
          persistentVolumeClaim:
            claimName: {{ .persistentVolumeClaim.claimName }}
            readOnly: {{ .persistentVolumeClaim.readOnly | default false }}
      {{- end }}
      containers:
        - name: postgres
          image: {{ include "helm-chart.postgres.image" . }}
          ports:
            - containerPort: {{ .Values.postgres.containerPort }}
          volumeMounts:
          {{- range .Values.postgres.volumeMounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              subPath: {{ .subPath | default "" }}
          {{- end }}
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgres.database }}
            - name: POSTGRES_USER
              value: {{ .Values.postgres.user }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.password }}
        - name: screenplay
          image: {{ include "helm-chart.frontend.image" . }}
          ports:
            - containerPort: {{ .Values.frontend.containerPort }}

        - name: screenplay-server
          image: {{ include "helm-chart.server.image" . }}
          ports:
            - containerPort: {{ .Values.server.containerPort }}
          readinessProbe:
{{ toYaml .Values.server.readinessProbe | indent 12 }}
          env:
            - name: SP_CONNECTIONSTRINGS__DEFAULTCONNECTION
              value: {{ include "helm-chart.postgres.connectionString" . }}
{{ toYaml .Values.server.env | indent 12 }}
          resources:
            requests:
{{- toYaml .Values.server.resources | nindent 12 }}
