---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm-chart.name" . }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "helm-chart.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "helm-chart.name" . }}
    spec:
      containers:
        - name: screenplay
          image: {{ .Values.frontend.image }}
          ports:
            - containerPort: {{ .Values.frontend.containerPort }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm-chart.name" . }}-server
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "helm-chart.name" . }}-server
  template:
    metadata:
      labels:
        app: {{ include "helm-chart.name" . }}-server
    spec:
      containers:
        - name: screenplay-server
          image: {{ .Values.server.image }}
          ports:
            - containerPort: {{ .Values.server.containerPort }}
          readinessProbe:
{{ toYaml .Values.server.readinessProbe | indent 12 }}
          livenessProbe:
{{ toYaml .Values.server.livenessProbe | indent 12 }}
          env:
            - name: SP_CONNECTIONSTRINGS__DEFAULTCONNECTION
              value: {{ include "helm-chart.postgres.connectionString" . }}
{{ toYaml .Values.server.env | indent 12 }}
          resources:
            requests:
{{- toYaml .Values.server.resources | nindent 12 }}
