apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-chart.name" . }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "helm-chart.name" . }}
    tier: frontend

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-chart.name" . }}-server
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: {{ .Values.server.service.targetPort }}
      protocol: TCP
      name: server
  selector:
    app: {{ include "helm-chart.name" . }}-server
    tier: backend
