apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-chart.fullname" . }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: {{ include "helm-chart.name" . }}
    tier: frontend

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-chart.fullname" . }}-server
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.server.service.port | quote }}
      targetPort: {{ .Values.server.service.targetPort | quote }}
      protocol: TCP
      name: postgres
  selector:
    app: {{ include "helm-chart.name" . }}
    tier: backend
